[tool.poetry]
name = "ansible-runner"
version = "1.4.6"
description = "Consistent Ansible Pythin API and CLI with container and process isoluation runtime capabilities"
homepage = ""
repository = "https://github.com/ansible/ansible-runner"
documentation = "https://ansible-runner.readthedocs.io/en/latest/"
license = "Apache-2.0"
authors = ["Red Hat Ansible"]
keywords = ["ansible", "runner"]
readme = "README.md"

[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
  | installer
  | packaging
)/
'''

[tool.poetry.dependencies]
python = "~2.7 || >=3.6"
psutil = "*"
pexpect = ">=4.5"
python-daemon = "*"
pyyaml = "*"
six = "*"

[tool.poetry.scripts]
ansible-runner = 'ansible_runner.__main__:main'

[tool.poetry.plugins."receptor.worker"]
ansible_runner = 'ansible_runner.receptor_plugin'

[tool.poetry.dev-dependencies]
more-itertools = "==5.0.0"
pytest = "==4.4.0"
pytest-xdist = "==1.32.0"
"flake8" = "*"
yamllint = "*"
funcsigs = "*"
mock = "*"
pathlib2 = "*"
scandir = "*"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
